post:
	ryu-manager --ofp-tcp-listen-port 6654 simple_switch_13_post.py
print:
	ryu-manager --ofp-tcp-listen-port 6654 simple_switch_13_print.py
rest:
	ryu-manager --ofp-tcp-listen-port 6654 rest_topology.py
