# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apcontrol.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'apcontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pcontrol.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\rAPInfoRequest\x12\x0c\n\x04\x64pid\x18\x01 \x01(\t\x12\x10\n\x08portName\x18\x02 \x01(\t\"\x1d\n\x0b\x41PInfoReply\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x07\x41PLinks\x12\x10\n\x08src_dpid\x18\x01 \x01(\t\x12\x10\n\x08\x64st_dpid\x18\x02 \x01(\t\x12\x0f\n\x07port_no\x18\x03 \x01(\x05\"-\n\x0f\x41PLinksResponse\x12\x1a\n\x08\x61p_links\x18\x01 \x03(\x0b\x32\x08.APLinks2v\n\tAPControl\x12/\n\rAPConnectMesh\x12\x0e.APInfoRequest\x1a\x0c.APInfoReply\"\x00\x12\x38\n\nGetAPLinks\x12\x16.google.protobuf.Empty\x1a\x10.APLinksResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apcontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APINFOREQUEST']._serialized_start=48
  _globals['_APINFOREQUEST']._serialized_end=95
  _globals['_APINFOREPLY']._serialized_start=97
  _globals['_APINFOREPLY']._serialized_end=126
  _globals['_APLINKS']._serialized_start=128
  _globals['_APLINKS']._serialized_end=190
  _globals['_APLINKSRESPONSE']._serialized_start=192
  _globals['_APLINKSRESPONSE']._serialized_end=237
  _globals['_APCONTROL']._serialized_start=239
  _globals['_APCONTROL']._serialized_end=357
# @@protoc_insertion_point(module_scope)
