# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mygrpc.python.apcontrol.apcontrol_pb2 as apcontrol__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in apcontrol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class APControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.APConnectMesh = channel.unary_unary(
                '/APControl/APConnectMesh',
                request_serializer=apcontrol__pb2.APInfoRequest.SerializeToString,
                response_deserializer=apcontrol__pb2.APInfoReply.FromString,
                _registered_method=True)


class APControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def APConnectMesh(self, request, context):
        """Mininet AP Run this 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'APConnectMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.APConnectMesh,
                    request_deserializer=apcontrol__pb2.APInfoRequest.FromString,
                    response_serializer=apcontrol__pb2.APInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'APControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('APControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class APControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def APConnectMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/APControl/APConnectMesh',
            apcontrol__pb2.APInfoRequest.SerializeToString,
            apcontrol__pb2.APInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
